# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassificationInterpretationEx": "01_classification-interpretation.ipynb",
         "intersection": "02_compare-models.ipynb",
         "compare_venn": "02_compare-models.ipynb",
         "Hook": "gradcam.ipynb",
         "HookBwd": "gradcam.ipynb",
         "create_test_img": "gradcam.ipynb",
         "compute_gcam_items": "gradcam.ipynb",
         "compute_gcam_map": "gradcam.ipynb",
         "plt_decoded": "gradcam.ipynb",
         "plot_gcam": "gradcam.ipynb",
         "GradCam": "gradcam.ipynb",
         "PathLike": "gradcam.ipynb"}

modules = ["interpret/interpret.py",
           "interpret/compare.py",
           "gradcam.py"]

doc_url = "https://rsomani95.github.io/fastai2_extensions/"

git_url = "https://github.com/rsomani95/fastai2_extensions/tree/master/"

def custom_doc_links(name): return None
