# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassificationInterpretationEx": "01_classification-interpretation.ipynb",
         "intersection": "02_compare-models.ipynb",
         "compare_venn": "02_compare-models.ipynb",
         "Hook": "03_gradcam.ipynb",
         "HookBwd": "03_gradcam.ipynb",
         "create_test_img": "03_gradcam.ipynb",
         "compute_gcam_items": "03_gradcam.ipynb",
         "compute_gcam_map": "03_gradcam.ipynb",
         "plt_decoded": "03_gradcam.ipynb",
         "plot_gcam": "03_gradcam.ipynb",
         "GradCam": "03_gradcam.ipynb",
         "PathLike": "04_export-to-other-frameworks.ipynb",
         "to_cuda": "04_export-to-other-frameworks.ipynb",
         "preprocess_one": "04_export-to-other-frameworks.ipynb",
         "preprocess_batch": "04_export-to-other-frameworks.ipynb",
         "open_image": "04_export-to-other-frameworks.ipynb",
         "torch_to_onnx": "04_export-to-other-frameworks.ipynb",
         "torch_to_numpy": "04_export-to-other-frameworks.ipynb",
         "onnx_to_tf": "04_export-to-other-frameworks.ipynb",
         "get_nn_spec": "04_export-to-other-frameworks.ipynb",
         "is_3dlut_row": "05_augment-PIL-img_filters.ipynb",
         "read_lut": "05_augment-PIL-img_filters.ipynb",
         "ApplyPILFilter": "05_augment-PIL-img_filters.ipynb"}

modules = ["interpret/interpret.py",
           "interpret/compare.py",
           "interpret/gradcam.py",
           "inference/export.py",
           "augment/pil_filters.py"]

doc_url = "https://rsomani95.github.io/fastai2_extensions/"

git_url = "https://github.com/rsomani95/fastai2_extensions/tree/master/"

def custom_doc_links(name): return None
