# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ClassificationInterpretationEx": "01-classification-interpretation.ipynb",
         "intersection": "02-compare-models.ipynb",
         "compare_venn": "02-compare-models.ipynb"}

modules = ["interpret.py",
           "interpret/compare.py"]

doc_url = "https://rsomani95.github.io/fastai2_extensions/"

git_url = "https://github.com/rsomani95/fastai2_extensions/tree/master/"

def custom_doc_links(name): return None
